name: crimebott
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  firebase_core: ^2.24.2
  http: ^1.2.0
  firebase_database: ^10.4.8
  firebase_storage: ^11.6.8
  provider: ^6.1.1
  # upgrade: ^0.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.9
  # location: ^5.0.3  
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.2
  image_picker: ^1.0.5
  # geolocator: ^11.0.0
  geocoding: ^2.0.0
  flutter_polyline_points: ^2.0.0
  flutter_typeahead: ^5.2.0
  dio: ^5.4.1
  tflite_flutter: ^0.10.4
  file_picker: ^6.2.0

  firebase_ml_model_downloader: ^0.2.5



  

 
  

  intl: any
  geodesy: ^0.10.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bdd_widget_test: ^1.2.1
  build_runner: ^2.3.3
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/icons/map-point.png
    - assets/background_img.jpg
    - assets/road.jpg
    - assets/best-fp16.tflite
   
 # fonts:
   # - family: MaterialIcons
    #  fonts:
     #   - asset: fonts/MaterialIcons-Regular.ttf
     #   - asset: fonts/MaterialIconsOutlined-Regular.codepoints
      #  - asset: fonts/MaterialIconsOutlined-Regular.otf
      #  - asset: fonts/MaterialIconsRound-Regular.codepoints
      #  - asset: fonts/MaterialIconsRound-Regular.otf
      #  - asset: fonts/MaterialIconsSharp-Regular.codepoints
      #  - asset: fonts/MaterialIconsSharp-Regular.otf
      #  - asset: fonts/MaterialIconsTwoTone-Regular.codepoints
      #  - asset: fonts/MaterialIconsTwoTone-Regular.otf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
